# This file was *autogenerated* from the file L04-plot04.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4)#!/usr/bin/env

p = plot(_sage_const_7 -_sage_const_4 *x,x,_sage_const_0 ,_sage_const_1 ,legend_label="$xu_1(r_1,s_1)+u_2(r_1,s_2)(1-x)$", color='red')
p += plot(_sage_const_6 -x,x,_sage_const_0 ,_sage_const_1 ,legend_label="$xu_1(r_2,s_1)+u_2(r_2,s_2)(1-x)$", color='blue')
p.axes_labels(['$x$','$u$'])
p.save("L04-plot04.png")
